const fs = require('fs');
const keys = JSON.parse(fs.readFileSync('bengali.json', 'utf8'));

const dict = {
  "Report ও এক্সপোর্ট": "Report & Export",
  "নোitemsফিকেশন ও রিমাইন্ডার": "Notifications & Reminders",
  "অ্যাপ Settings ও প্রিফারেন্স": "App Settings & Preferences",
  "আপনি কি ডিফল্ট স্যাম্পল ডাটায় রিসেট করতে চান?": "Are you sure you want to reset to default sample data?",
  "রিসেট ডাটা": "Reset Data",
  "টু-ডু ({String(todoCount)})": "To-Do ({String(todoCount)})",
  "চলমান ({String(inProgressCount)})": "In Progress ({String(inProgressCount)})",
  "কাজের শিরোনাম, ক্যাটাগরি দিয়ে খুঁজুন...": "Search by task title, category...",
  "সকল Staffের কাজ": "All Staff Tasks",
  "সকল প্রায়োরিitems": "All Priorities",
  "কোনো Tasks পাওয়া যায়নি। নতুন Tasks তৈরি করতে বাটনে ক্লিক করুন।": "No tasks found. Click the button to create new tasks.",
  "আনচেক করুন": "Uncheck",
  "Tasks Completed মার্ক করুন": "Mark Task as Completed",
  "সকল Staff": "All Staff",
  "নতুন (To-Do)": "New (To-Do)",
  "চলমান (In Progress)": "In Progress",
  "এই Tasksitems মুছে ফেলতে চান?": "Are you sure you want to delete this task?",
  "Tasks মুছুন": "Delete Task",
  "সাব-Tasks Checklist ({String(completedSubCount)}/{String(task.subtasks.length)})": "Sub-task Checklist ({String(completedSubCount)}/{String(task.subtasks.length)})",
  "আব্দুল করিম": "Abdul Karim",
  "হেড Manager / শাখা ইনচার্জ": "Head Manager / Branch In-Charge",
  "মোহাম্মদ রফিক উল্লাহ": "Mohammad Rafiq Ullah",
  "প্রধান শেফ / মাস্টার কারিগর": "Head Chef / Master Craftsman",
  "কিচেন ও প্রোডাকশন": "Kitchen & Production",
  "সকাল ৭:০০ - বিকাল ৩:০০": "7:00 AM - 3:00 PM",
  "তানভীর আহমেদ": "Tanvir Ahmed",
  "সিনিয়র ক্যাশিয়ার ও একাউন্ট্যান্ট": "Senior Cashier & Accountant",
  "সকাল ১০:০০ - রাত ৮:০০": "10:00 AM - 8:00 PM",
  "সালমা জাহান": "Salma Jahan",
  "সেলস ও কাস্টমার সার্ভিস অফিসার": "Sales & Customer Service Officer",
  "সকাল ৮:০০ - বিকাল ৪:০০": "8:00 AM - 4:00 PM",
  "ধানমন্ডি আউটলেট": "Dhanmondi Outlet",
  "জাহিদ হোসেন": "Jahid Hossain",
  "ডেলিভারি ইনচার্জ ও রাইডার": "Delivery In-Charge & Rider",
  "ডেলিভারি ও লজিস্itemsকস": "Delivery & Logistics",
  "সকাল ১০:০০ - রাত ৯:০০": "10:00 AM - 9:00 PM",
  "মোবারক আলী": "Mobarak Ali",
  "স্টোর ও ইনভেন্টরি কিপার": "Store & Inventory Keeper",
  "স্টোর ও সাপ্লাই": "Store & Supply",
  "সকাল ৮:০০ - বিকাল ৫:০০": "8:00 AM - 5:00 PM",
  "মিরপুর শোরুম": "Mirpur Showroom",
  "সঠিক সময়ে Present, সকালের স্টোর পরিদর্শন Completed।": "Present on time, morning store inspection completed.",
  "সকাল ৭টার আগেই প্রোডাকশন শুরু করেছেন।": "Started production before 7 AM.",
  "রাস্তায় জ্যামের কারণে ২৫ মিনিট বিলম্ব।": "Late by 25 minutes due to traffic jam.",
  "কাউন্টার প্রস্তুত ও পরিষ্কার Completed।": "Counter ready and cleaning completed.",
  "আজকের ডেলিভারি শিডিউল সংগ্রহ করেছেন।": "Collected today's delivery schedule.",
  "অফিসিয়াল অসুস্থতাperson(s)িত অগ্রিম অনুমোদিত ছুitems (Sick Leave)।": "Official pre-approved sick leave.",
  "Urgent: খাদ্য নিরাপত্তা, হাইজিন ও ডিসপ্লে গাইডলাইন": "Urgent: Food Safety, Hygiene & Display Guidelines",
  "সকল কাউন্টার ও কিচেন Staffদের সর্বদা এপ্রন, হেয়ারনেট এবং গ্লাভস পরিধান করতে হবে। প্রতিitems ডিসপ্লে ক্যাবিনেটের কাঁচ প্রতি ২ ঘণ্টা অন্তর স্যানিটাইজ করা বাধ্যতামূলক। কোনো মেয়াদোত্তীর্ণ পণ্য ডিসপ্লেতে রাখা যাবে না।": "All counter and kitchen staff must always wear aprons, hairnets, and gloves. Sanitizing display cabinet glass every 2 hours is mandatory. Expired products cannot be kept on display.",
  "হেয়ারনেট ও হ্যান্ড গ্লাভস নিশ্চিতকরণ": "Ensure Hairnet & Hand Gloves",
  "ডিসপ্লে কাউন্টার প্রতি ২ ঘণ্টায় জীবাণুমুক্তকরণ": "Sanitize Display Counter Every 2 Hours",
  "তাপমাত্রা ও ফ্রিজার রিডিং লগ খাতায় লিপিবদ্ধকরণ": "Record Temperature & Freezer Reading in Log",
  "দৈনিক ক্যাশ ক্লোজিং ও রসিদ মেলানোর বিশেষ নির্দেশনা": "Special Directive for Daily Cash Closing & Receipt Matching",
  "সন্ধ্যা ৮:৩০ মিনিটে ক্যাশ কাউন্ট শেষ করে সফটওয়্যারের সেলস Reportের সাথে ক্যাশ, কার্ড ও বিকাশ পেমেন্ট পুঙ্খানুপুঙ্খভাবে মিলিয়ে Manager বরাবর Report জমা দিতে হবে। কোনোরূপ মিসম্যাচ থাকলে সাথে সাথে নোট করতে হবে।": "Finish cash count at 8:30 PM and match cash, card, and bKash payments thoroughly with software sales report before submitting to the Manager. Any mismatch must be noted immediately.",
  "হেড অফিস": "Head Office",
  "পিওএস (POS) সামারি প্রিন্ট নেওয়া": "Take POS Summary Print",
  "বিকাশ ও ব্যাংক কিউআর ট্রানজেকশন ভেরিফাই": "Verify bKash & Bank QR Transactions",
  "লক ভল্টে ক্যাশ জমা ও Manager স্বাক্ষর": "Deposit Cash in Lock Vault & Get Manager Signature",
  "কাস্টমার অভ্যর্থনা ও অমায়িক ব্যবহার প্রটোকল": "Customer Reception & Polite Behavior Protocol",
  "দিলখুশের প্রতিitems ক্রেতাকে হাসিমুখে": "Welcome every Dilkhoosh customer with a smile",
  "জানিয়ে গ্রহণ করুন। অর্ডার ডেলিভারির পর": "Welcome them. After order delivery,",
  "বলুন। অভিযোগ থাকলে বিনয়ের সাথে শুনুন এবং ইনচার্জকে জানান।": "Say it. Listen to complaints politely and inform the in-charge.",
  "সকালের ফ্রেশ মিষ্items ও বেকারি আইটেম ইনভেন্টরি চেকিং": "Morning Fresh Sweets & Bakery Item Inventory Checking",
  "কারখানা থেকে আসা সকালের তাজা মিষ্itemsর লট কাউন্ট করে সেলস ট্রেতে সাজিয়ে রাখা ও ডেট স্ট্যাম্প লাগানো।": "Count fresh morning sweets batch from factory, arrange on sales trays, and apply date stamp.",
  "রসগোল্লা ও সন্দেশের ব্যাচ টেস্ট": "Batch test of Rosogolla & Sondesh",
  "ওperson(s) ও ট্রের সংখ্যা মিলিয়ে গ্রহণ": "Receive by matching weight & tray count",
  "ডিসপ্লেতে মূল্য ট্যাগ যাচাই": "Verify price tag on display",
  "ক্যাশ রেজিস্টার ব্যালেন্সিং ও ভাউচার চেক": "Cash Register Balancing & Voucher Check",
  "গতকালের ভেন্ডর পেমেন্ট ভাউচার ফাইলিং এবং সকালের ক্যাশ ফ্লো রেজিস্টারে এন্ট্রি Completed করা।": "File yesterday's vendor payment vouchers and complete entry in morning cash flow register.",
  "হিসাব": "Accounts",
  "সকালের নগদ ৫০০ টাকার নোট ফ্লো নিশ্চিতকরণ": "Ensure morning cash flow of 500 Taka notes",
  "দুধ ও ময়দা সরবরাহকারীর ইনভয়েস এন্ট্রি": "Milk & Flour Supplier Invoice Entry",
  "কর্পোরেট গিফট বক্স ডেলিভারি ও রিসিট সংগ্রহ": "Corporate Gift Box Delivery & Receipt Collection",
  "গ্রাহকের নির্ধারিত ৩items প্রিমিয়াম মিষ্items বক্স দুপুর ১২টার মধ্যে গুলশান অফিসে সরবরাহ করা।": "Deliver customer's designated 3 premium sweet boxes to Gulshan office by 12 PM.",
  "বক্স সিল ও রিবন প্যাকিং নিশ্চিতকরণ": "Ensure Box Seal & Ribbon Packing",
  "গ্রাহকের ফোনে কনফার্মেশন কল": "Confirmation Call to Customer's Phone",
  "স্বাক্ষরিত ডেলিভারি স্লিপ জমা": "Submit Signed Delivery Slip",
  "কাউন্টার ডিসপ্লে রিলোড ও প্যাকেট স্টক গোছানো": "Counter Display Reload & Packet Stock Arrangement",
  "গ্রাহকদের ভিড়ের আগে ১ কেজি ও আধা কেজির মিষ্itemsর খালি বক্স ফোল্ড করে সাজিয়ে রাখা।": "Fold and arrange empty 1kg and 500g sweet boxes before customer rush.",
  "৫০items মিষ্itemsর প্যাকেট রেডি করা": "Ready 50 packets of sweets",
  "ক্যারি ব্যাগ কাউন্টারে রাখা": "Keep Carry Bags at Counter",
  "উত্তরা এক্সপ্রেস ব্রাঞ্চ": "Uttara Express Branch"
};

const fullDict = {};
keys.forEach(k => {
  fullDict[k] = dict[k] || k;
});

fs.writeFileSync('dict.json', JSON.stringify(fullDict, null, 2));
